<a href="https://colab.research.google.com/github/rashmi-reddie/foodapp/blob/main/00_pytorch_fundamentals_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello !! Iam very excited to learn PyTorch!")

Hello !! Iam very excited to learn PyTorch!


In [1]:
print("Hello !! Iam very excited to learn PyTorch!")

Hello !! Iam very excited to learn PyTorch!


##Introduction to tensors
### Creating tensors
pyTorch tensors are created using "torch.Tensor()' ="https://docs.pytorch.org/docs/stable/tensors.html"


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [5]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#get tensor back as an item int
scalar.item()

7

In [8]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
#no.of pairs of square brackets:ndim
vector.ndim

1

In [10]:
#(of rank 1) has shape (n)=> n is no.of elements
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
#(rank 2 tensor) has a shape like (rows,columns)
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

#creating random tensors
####tensors are very imp in neural networks coz the way neural networks learn is that they start with tensors full of random numbers and adjust those numbers to better represent data.
######start with random num-> look at data -> upd rand num -> look at data -> upd rand num
###Torch random Tensors -> https://docs.pytorch.org/docs/stable/generated/torch.rand.html

```
# This is formatted as code
```



In [19]:
#tensor shape : "https://www.google.com/search?q=torch.shape&sca_esv=cba8e83070f3f7ab&sxsrf=AE3TifN8kvqGeMSoTKqOYP4LIWlPpt6b4Q%3A1754041564202&ei=3IyMaLKQDOCTseMPmMn7yAQ&sclient=gws-wiz-serp&udm=50&fbs=AIIjpHxU7SXXniUZfeShr2fp4giZ1Y6MJ25_tmWITc7uy4KIeioyp3OhN11EY0n5qfq-zEMZldv_eRjZ2XLYc5GnVnME7glWodDcaQwvGYJtospyF4hao4VocMoniUVvlzzwRcCLYvfsjPeiuln4CZ9mxRNzMJl71rp-WEM_b89yTboF0wE9FSbwRYrSVuB6YHexvLk_d7r_74zDurdYUrhSbdL5TbQGiA&ved=2ahUKEwirmsKYsumOAxURRWwGHY2vAEEQ0NsOegQIExAA&aep=10&ntc=1&mtid=oJWMaILZCa2eseMPvdb_sA4&mstk=AUtExfBSmKXRpf8QbqQdGPUSDjujBDISEZaXP2EUItob_2tVp2YQzQ_5dQwDulglnGijroYC-GO6SdZws11YDFPgMHjmmaxV3SF6klmvDSzCBY6-2RMRgShbBavStYJKEuhAYvD9hNdh4CGM1CbV1fQ03WvT794RKEtTIPsRmXHrkxKuTDdZHAN0DWhRrap8o1hYZ49FMrRvo2LKL0zb7wfBqcqYnV3IvHoly8DppDMxG-iKehpnw-JsT0DipI92_qAJne-Ucwds5rjuUsil0zyhaIcZ9D5rfDRfsAvkx1hx4fNB4gNDiWSOPA7Y2VcLXXVvNurdOTUAy96M6Q&csuir=1"
TENSOR.shape

torch.Size([1, 3, 3])

In [3]:
!nvidia-smi

Fri Aug  1 09:38:49 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----